apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: govbiz-portfolio-core-service, namespace: argocd}
spec:
  project: govbiz-portfolio
  source:
    repoURL: https://github.com/GovBiz-Team/GovBiz-infra.git
    targetRevision: develop
    path: charts/govbiz-service
    helm:
      releaseName: core-service
      valueFiles: [../../environments/portfolio/core-service.yaml]
  destination: {server: https://kubernetes.default.svc, namespace: govbiz-msa}
  syncPolicy:
    automated: {enabled: true, prune: false, selfHeal: true}
    syncOptions: [FailOnSharedResource=true]
    retry:
      limit: 5
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: govbiz-portfolio-catalog-service, namespace: argocd}
spec:
  project: govbiz-portfolio
  source:
    repoURL: https://github.com/GovBiz-Team/GovBiz-infra.git
    targetRevision: develop
    path: charts/govbiz-service
    helm:
      releaseName: catalog-service
      valueFiles: [../../environments/portfolio/catalog-service.yaml]
  destination: {server: https://kubernetes.default.svc, namespace: govbiz-msa}
  syncPolicy:
    automated: {enabled: true, prune: false, selfHeal: true}
    syncOptions: [FailOnSharedResource=true]
    retry:
      limit: 5
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: govbiz-portfolio-ai-service, namespace: argocd}
spec:
  project: govbiz-portfolio
  source:
    repoURL: https://github.com/GovBiz-Team/GovBiz-infra.git
    targetRevision: develop
    path: charts/govbiz-service
    helm:
      releaseName: ai-service
      valueFiles: [../../environments/portfolio/ai-service.yaml]
  destination: {server: https://kubernetes.default.svc, namespace: govbiz-msa}
  syncPolicy:
    automated: {enabled: true, prune: false, selfHeal: true}
    syncOptions: [FailOnSharedResource=true]
    retry:
      limit: 5
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: govbiz-portfolio-ops-service, namespace: argocd}
spec:
  project: govbiz-portfolio
  source:
    repoURL: https://github.com/GovBiz-Team/GovBiz-infra.git
    targetRevision: develop
    path: charts/govbiz-service
    helm:
      releaseName: ops-service
      valueFiles: [../../environments/portfolio/ops-service.yaml]
  destination: {server: https://kubernetes.default.svc, namespace: govbiz-msa}
  syncPolicy:
    automated: {enabled: true, prune: false, selfHeal: true}
    syncOptions: [FailOnSharedResource=true]
    retry:
      limit: 5
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
