apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: govbiz-local
resources:
  - ../../services/ops-service/base
configMapGenerator:
  - name: ops-service-config
    literals:
      - DJANGO_DEBUG=false
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,ops-service,ops-service.govbiz-local.svc.cluster.local
      - DB_NAME=govbiz_ops
      - DB_USER=govbiz_ops
      - DB_HOST=ops-mysql
      - DB_PORT=3306
images:
  - name: govbiz-ops-service
    newTag: local-k8s
