apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: govbiz-local
resources:
  - service.yaml
  - statefulset.yaml
configMapGenerator:
  - name: ops-mysql-config
    literals:
      - MYSQL_DATABASE=govbiz_ops
      - MYSQL_USER=govbiz_ops
