apiVersion: v1
kind: Service
metadata:
  name: {{ required "serviceName is required" .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
